/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Atributos.Devedores;
import Atributos.Enderecos;
import Atributos.Telefones;
import Banco.ClientesDAO;
import Banco.DevedoresDAO;
import Banco.EnderecosDAO;
import Banco.TelefonesDAO;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.AbstractCellEditor;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author User
 */
public class ListaDevedores extends JDialog {

    
    
    /**
     * Creates new form CadastroDevedores
     */
    public ListaDevedores() {
        initComponents();
        desativaCampos();
    }
    
    public ListaDevedores(int idDevedores, JDialog owner) {
        super(owner, "Listagem de devedores", true);
        initComponents();
        desativaCampos();
        listaDevedoresPorID(idDevedores);
    }
    
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel modelTelefones = new DefaultTableModel();
    DefaultTableModel modelEnderecos = new DefaultTableModel();

    
    private void desativaCampos(){
        jTFNome.setEditable(false);
        jTFDevedorCliente.setEditable(false);
        jTFCPFCNPJ.setEditable(false);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFCPFCNPJ = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTelefones = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTEnderecos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTFDevedorCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFPesquisar = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTDevedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do devedor"));

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF/CNPJ:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefones e E-mails"));

        jTTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cadastrado por", "Telefone", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTTelefones);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereços"));

        jTEnderecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cadastrado por", "Rua", "Número", "Complemento", "Bairro", "Cidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTEnderecos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Novo Devedor");

        jButton2.setText("Alterar dados");

        jButton3.setText("Desativar");

        jLabel4.setText("Cliente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTFNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                                    .addComponent(jTFCPFCNPJ, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFDevedorCliente))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTFNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFCPFCNPJ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTFDevedorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jLabel3.setText("Pesquisar Devedor:");

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jTDevedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Nome", "CPF/CNPJ", "Saldo Devedor", "Ação de Cobrança"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTDevedores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTDevedores.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = jTDevedores.getSelectedRow();
                    if (selectedRow != -1) {
                        jTFDevedorCliente.setText(String.valueOf(jTDevedores.getValueAt(selectedRow, 0)));
                        jTFNome.setText((String) jTDevedores.getValueAt(selectedRow, 1));
                        jTFCPFCNPJ.setText((String) jTDevedores.getValueAt(selectedRow, 2));
                        pesquisarTelefones(String.valueOf(jTDevedores.getValueAt(selectedRow,0)),String.valueOf((jTDevedores.getValueAt(selectedRow, 2))));
                        pesquisarEnderecos(String.valueOf(jTDevedores.getValueAt(selectedRow,0)),String.valueOf((jTDevedores.getValueAt(selectedRow, 2))));
                    }
                }
            }
        });
        jScrollPane3.setViewportView(jTDevedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPesquisar))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        pesquisar("%"+jTFPesquisar.getText()+"%");
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void listaDevedoresPorID(int idDevedor){
        DevedoresDAO devedorDAO = new DevedoresDAO();
        Devedores devedor = new Devedores();

        ClientesDAO clienteDAO = new ClientesDAO();
        ArrayList<Devedores> listaDevedores = devedorDAO.buscaDevedorPorId(idDevedor);
        model = (DefaultTableModel) jTDevedores.getModel();
        model.setNumRows(0);

        model.addRow(new Object[]{
            clienteDAO.buscaNomeCliente(listaDevedores.get(0).getIdCliente()),
            listaDevedores.get(0).getNomeDevedor(),
            listaDevedores.get(0).getCpfcnpj(),
            listaDevedores.get(0).getSaldoDevedor(),
            "Ação de Cobrança"
        });
        
        jTDevedores.setRowSelectionInterval(0, 0);
        // Configuração do renderizador personalizado para a coluna do botão
        jTDevedores.getColumn("Ação de Cobrança").setCellRenderer(new ListaDevedores.BotaoRenderer());

        // Configuração do editor de célula para a coluna do botão
        jTDevedores.getColumn("Ação de Cobrança").setCellEditor(new ListaDevedores.BotaoEditor());
    }
    
    private void pesquisarEnderecos(String nomeCliente, String cpfcnpj){
        DevedoresDAO devedorDAO = new DevedoresDAO();
        ClientesDAO clienteDAO = new ClientesDAO();
        int idCliente = clienteDAO.buscaIdClientePorCPF(cpfcnpj);
        int idDevedor = devedorDAO.buscaIdDevedor(cpfcnpj);
        
        EnderecosDAO endDAO = new EnderecosDAO();
        Enderecos end = new Enderecos();
        
        ArrayList<Enderecos> listaEnd = endDAO.buscaEndDevedor(idDevedor);
        modelEnderecos = (DefaultTableModel) jTEnderecos.getModel();
        modelEnderecos.setNumRows(0);
        for (int i = 0; i < listaEnd.size(); i++) {
            modelEnderecos.addRow(new Object[]{
                clienteDAO.buscaNomeCliente(listaEnd.get(i).getIdCliente()),
                listaEnd.get(i).getRua(),
                listaEnd.get(i).getNumero(),
                listaEnd.get(i).getComplemento(),
                listaEnd.get(i).getBairro(),
                listaEnd.get(i).getCidade()
            });
        }
    }
    
    private void pesquisarTelefones(String nomeCliente, String cpfcnpj){
        DevedoresDAO devedorDAO = new DevedoresDAO();
        ClientesDAO clienteDAO = new ClientesDAO();
        int idCliente = clienteDAO.buscaIdClientePorCPF(cpfcnpj);
        int idDevedor = devedorDAO.buscaIdDevedor(cpfcnpj);
        
        TelefonesDAO telDAO = new TelefonesDAO();
        Telefones tel = new Telefones();
        
        ArrayList<Telefones> listaTel = telDAO.buscaTelefoneDevedor(idDevedor);
        modelTelefones = (DefaultTableModel) jTTelefones.getModel();
        modelTelefones.setNumRows(0);
        for (int i = 0; i < listaTel.size(); i++) {
            modelTelefones.addRow(new Object[]{
                clienteDAO.buscaNomeCliente(listaTel.get(i).getIdCliente()),
                listaTel.get(i).getTelefone(),
                listaTel.get(i).getEmail()
            });
        }
    }
    
    private void pesquisar(String busca){
        DevedoresDAO devedorDAO = new DevedoresDAO();
        Devedores devedor = new Devedores();

        ClientesDAO clienteDAO = new ClientesDAO();
        ArrayList<Devedores> listaDevedores = devedorDAO.buscaDevedorPorNome(busca);
        model = (DefaultTableModel) jTDevedores.getModel();
        model.setNumRows(0);
        for (int i = 0; i < listaDevedores.size(); i++) {
            model.addRow(new Object[]{
                clienteDAO.buscaNomeCliente(listaDevedores.get(i).getIdCliente()),
                listaDevedores.get(i).getNomeDevedor(),
                listaDevedores.get(i).getCpfcnpj(),
                listaDevedores.get(i).getSaldoDevedor(),
                "Ação de Cobrança"
            });
        }
        // Configuração do renderizador personalizado para a coluna do botão
        jTDevedores.getColumn("Ação de Cobrança").setCellRenderer(new ListaDevedores.BotaoRenderer());

        // Configuração do editor de célula para a coluna do botão
        jTDevedores.getColumn("Ação de Cobrança").setCellEditor(new ListaDevedores.BotaoEditor());
        
    }
    
    private JDialog retornaTela(){
        return this;
    }
    
    // Editor de célula personalizado para lidar com o evento de clique do botão
    class BotaoEditor extends AbstractCellEditor implements TableCellEditor {
        private JButton button;

        public BotaoEditor() {
            button = new JButton();
            button.setOpaque(true);

            // Adiciona um ActionListener ao botão
            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    ClientesDAO cliDAO = new ClientesDAO();
                    int idCliente = cliDAO.buscaIdClientePorCPF(jTDevedores.getValueAt(jTDevedores.getSelectedRow(), 1).toString());
                    
                    DevedoresDAO creDAO = new DevedoresDAO();
                    int idDevedor = creDAO.buscaIdDevedor(jTDevedores.getValueAt(jTDevedores.getSelectedRow(), 2).toString());
                    
                    ListaAcoesCobranca tela = new ListaAcoesCobranca(idCliente, idDevedor, retornaTela());
                    tela.setVisible(true);
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            return null;
        }    
    }
    
    // Renderizador personalizado para exibir o botão na célula da tabela
    class BotaoRenderer extends JButton implements TableCellRenderer {
        public BotaoRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText("Abrir");
            return this;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDevedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDevedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDevedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDevedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDevedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTDevedores;
    private javax.swing.JTable jTEnderecos;
    private javax.swing.JTextField jTFCPFCNPJ;
    private javax.swing.JTextField jTFDevedorCliente;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPesquisar;
    private javax.swing.JTable jTTelefones;
    // End of variables declaration//GEN-END:variables
}
